name: music-mix-analyzer

services:
  music-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-analyzer
    restart: always
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - GUNICORN_WORKERS=4
      - GUNICORN_THREADS=8
      - GUNICORN_TIMEOUT=300
      - GUNICORN_MAX_REQUESTS=1000
      - GUNICORN_MAX_REQUESTS_JITTER=50
      # Environment identification
      - RUN_ENV=production
      # Security settings
      - FORCE_HTTPS=true
      # Database connection for production
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=mixanalytic_db
      - MYSQL_PASSWORD=FH[@q#Z4YzQq1@8#
      - MYSQL_DATABASE=music_analyzer
      # Analytics
      - ENABLE_ANALYTICS=true
      - MATOMO_URL=https://seo.optagonen.se
      - MATOMO_SITE_ID=3
      # Fix for Matplotlib and numba caching issues
      - MPLCONFIGDIR=/tmp/matplotlib
      - NUMBA_CACHE_DIR=/tmp/numba_cache
    volumes:
      - ./uploads:/app/uploads
      - ./config:/app/config
      - ./logs:/app/logs
    tmpfs:
      - /tmp:exec,size=1G
      - /dev/shm:size=2G
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "5"

  db:
    image: mysql:8.0
    container_name: music-analyzer-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=music_analyzer
      - MYSQL_USER=music_user
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password --sql-mode="NO_ENGINE_SUBSTITUTION"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE to avoid "mbind: Operation not permitted"

volumes:
  mysql_data:
    driver: local 