version: '3'

services:
  music-analyzer:
    build: .
    container_name: music-analyzer
    ports:
      - "127.0.0.1:5001:5000"
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - music_data:/app/static/uploads
      - ./logs:/var/log/app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - MAX_UPLOAD_SIZE=100MB
      - GUNICORN_CMD_ARGS="--access-logfile /var/log/app/access.log --error-logfile /var/log/app/error.log --log-level debug"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  music_data:
    driver: local 