version: '3'

services:
  music-analyzer:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    container_name: music-analyzer
    restart: unless-stopped
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - GUNICORN_TIMEOUT=300
      - GUNICORN_MAX_REQUESTS=1000
      - GUNICORN_MAX_REQUESTS_JITTER=50
    volumes:
      - ../..:/app
      - ../../uploads:/app/uploads
    tmpfs:
      - /tmp:exec,size=1G
      - /dev/shm:size=2G
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

volumes:
  music_data:
    driver: local 